### ISSUE TITLE
Not an issue but just a general question!

### ISSUE THREAD

**Issue by TripleT-circuitmaker** [FleshdeckTV/nRF52-Smartwatch#1]
Hello!

I am working on my own little project for college which involves using the NRF52832 microcontroller and the GC9A01 LCD display, however, I cannot seem to get them to work with GIFs specifically.

I am currently programming this on the Arduino IDE using the Arduino_GFX library and I wanted to know if you can possibly share some insight on how to resolve this issue?

My main goal is just to display GIFs on the screen.
I am using the included ImageViewerAnimatedGIF example project (modified so it works with my board and LCD) however I can't display GIF's larger than 64 x 64. I'm trying to display 240 x 240 GIFs. The NRF I'm working with has 64 KB SRAM. How were you able to display so many things on your screen? 

Please let me know if there is any advice or insight you can provide!

**Comment by FleshdeckTV** [comment]
Hello, I'm using nrf52840, there is 256 kb of RAM, to draw pictures of 240x240 pixels you need more than 100 kb of RAM
